In [30]:
import numpy as np
from sklearn import metrics

In [31]:
def to_one_hot(x, size):
    b = np.zeros((x.size, size))
    b[np.arange(x.size),x] = 1
    return b

In [32]:
ncls = 10
nrows = 100
size = (nrows, ncls)

x = np.random.random(size)
y = (np.random.random(size) - 0.5) * 0.1 + x

In [33]:
mxx = x.argmax(axis=1)
mxy = y.argmax(axis=1)

print(mxx)
print(mxy)

sum(mxx == mxy) / nrows

[6 5 6 7 2 2 8 0 5 3 3 9 1 3 3 1 4 0 6 2 8 1 9 4 6 1 7 3 1 6 8 8 6 6 2 7 1
 6 5 2 0 4 3 5 3 3 8 0 0 2 8 1 4 5 3 0 0 9 5 3 6 7 3 5 5 2 2 7 8 0 5 9 0 5
 2 9 8 7 9 7 5 5 7 0 7 0 8 7 3 4 8 4 2 9 9 4 4 6 2 9]
[6 5 6 7 2 2 8 0 5 2 3 9 1 2 3 1 9 5 6 2 8 1 9 4 6 1 7 3 1 6 8 8 6 6 2 7 1
 6 5 2 0 4 3 5 1 0 8 0 0 2 5 1 5 5 3 0 0 9 5 3 6 8 3 9 5 0 2 4 8 0 5 9 0 5
 2 9 8 0 9 7 5 5 7 0 7 0 8 7 3 4 8 4 2 9 6 4 4 6 2 9]


0.86

In [34]:
conf = np.zeros((ncls, ncls))
for i in range(len(mxx)):
    conf[mxx[i]][mxy[i]] += 1
conf

array([[10.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  2.,  8.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  6.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  1.,  0.,  0.,  7.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  9.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  8.]])

In [35]:
tp = np.zeros((ncls,))
fn = np.zeros((ncls,))
fp = np.zeros((ncls,))
precision = np.zeros((ncls,))
recall = np.zeros((ncls,))

for i_real in range(ncls):
    for i_pred in range(ncls):
        value = conf[i_real][i_pred]
        if i_real == i_pred:
            tp[i_real] = value
        else:
            fn[i_real] += value
            fp[i_pred] += value

fn[fn == 0] = 1.e-09
fp[fp == 0] = 1.e-09

recall = tp / (tp + fn)
precision = tp / (tp + fp)

p_macro = sum(precision) / ncls
r_macro = sum(recall) / ncls

f_macro = 2 * p_macro * r_macro / (p_macro + r_macro)

In [36]:
print(tp)
print(fn)
print(recall)
print(f_macro)

[10.  7. 10.  8.  6. 11. 10.  7.  9.  8.]
[1.e+00 1.e-09 1.e+00 4.e+00 2.e+00 1.e+00 1.e-09 3.e+00 1.e+00 1.e+00]
[0.90909091 1.         0.90909091 0.66666667 0.75       0.91666667
 1.         0.7        0.9        0.88888889]
0.8684729533751236


In [37]:
fn[3] = 0
fn[fn == 0] = 1.e-09
fn

array([1.e+00, 1.e-09, 1.e+00, 1.e-09, 2.e+00, 1.e+00, 1.e-09, 3.e+00,
       1.e+00, 1.e+00])

In [41]:
mxy_onehot = to_one_hot(mxy, ncls)
mxx_onehot = to_one_hot(mxx, ncls)

mxy_onehot.shape

(100, 10)

In [40]:
f1 = metrics.f1_score(mxy_onehot, mxx_onehot, average='macro')
f1

0.8600401357515371

In [7]:
confmat = metrics.confusion_matrix(mxx, mxy)
confmat

array([[5, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 6, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4]])

In [29]:
steps = 3.33
for batch_i in range(int(steps)+1):
    if (batch_i + 1) % (int(steps / 4) + 1) == 0:
        print(batch_i)

0
1
2
3
