In [41]:
from pettingzoo.classic.connect_four import connect_four
import numpy as np

In [49]:

env = connect_four.env()
env.reset()

In [29]:
x = env.step(1)
x = env.step(4)

In [30]:
x = env.last()

In [31]:
env.render()

player_0's turn'
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 1 1 1 0 0]]


In [33]:
legal_actions = x[0]['action_mask']

In [35]:
legal_actions[1] = 0

In [47]:
np.random.choice(legal_actions.nonzero()[0], 100)

array([0, 6, 0, 5, 2, 5, 5, 3, 6, 4, 0, 0, 4, 5, 3, 2, 4, 4, 0, 0, 2, 6,
       6, 0, 6, 2, 3, 6, 2, 3, 4, 2, 4, 4, 6, 6, 0, 0, 3, 2, 4, 5, 2, 5,
       4, 3, 5, 4, 5, 5, 4, 2, 3, 6, 4, 5, 6, 3, 3, 4, 4, 2, 2, 3, 0, 4,
       2, 5, 5, 6, 0, 6, 4, 0, 0, 4, 3, 3, 0, 2, 3, 2, 6, 4, 6, 0, 2, 3,
       5, 5, 0, 2, 3, 2, 5, 3, 2, 0, 0, 3])

In [50]:
env.dones

{'player_0': False, 'player_1': False}

In [51]:
env.dones[env.agent_selection]

False

In [53]:

env.env_done

False

In [54]:
env.rewards

{'player_0': 0, 'player_1': 0}