In [1]:
import numpy as np
import matplotlib.pyplot as plt
from random import random
from torch.utils.data import DataLoader
from lib.mnist_aug.mnist_augmenter import DataManager
from skimage.transform import resize

In [2]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

loader = DataLoader(data, batch_size=4, shuffle=True)

In [3]:
for i_batch, sample_batched in enumerate(loader):
    print(i_batch)
    print(sample_batched)
    print()

0
tensor([5, 4, 0, 1])

1
tensor([6, 7, 9, 3])

2
tensor([8, 2])

