In [59]:
from pettingzoo.classic import connect_four_v3
import numpy as np
from app.rl.dqn.games.train_gridworld import GridWorldEnvWrapper

In [2]:
env = connect_four_v3.env()

In [8]:
x = env.reset()
print(x)

None


In [5]:
agent0 = env.agents[0]
agent0

'player_0'

In [9]:
env.agent_selection

'player_0'

In [11]:
for i in range(100):
    env.reset()
    print(env.agent_selection)

# So the first player who makes the move is always player0

player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0
player_0


In [35]:
env.reset()
for i in range(6):
    env.step(0)
    env.render()

player_1's turn'
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
player_0's turn'
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
player_1's turn'
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
player_0's turn'
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
player_1's turn'
[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]
player_0's turn'
[[2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]


In [42]:
x = env.observe(env.agent_selection)

In [43]:
x.keys()

dict_keys(['observation', 'action_mask'])

In [44]:
x['action_mask']

array([0, 1, 1, 1, 1, 1, 1])

In [47]:
np.nonzero(x['action_mask'])[0]

array([1, 2, 3, 4, 5, 6])

In [51]:
x = env.step(2)
x

In [53]:
env.rewards['player_0']

0

In [54]:
env.infos

{'player_0': {}, 'player_1': {}}

In [56]:
env.metadata

{'render.modes': ['human', 'ansi'], 'name': 'connect_four_v3'}

In [61]:
gw = GridWorldEnvWrapper()

In [64]:
gw.env.metadata

{'render.modes': []}